### ISSUE TITLE
trim(): Passing null to parameter #1 ($string) of type string is deprecated error on $email == null

### ISSUE THREAD

**Issue by eelco2k** [awcodes/filament-gravatar#1]
error:
```
trim(): Passing null to parameter #1 ($string) of type string is deprecated
```
in Gravatar.php

```
$url .= md5(strtolower(trim($email)));
```

my workaround for now:

```
if ($email) {
   $url .= md5(strtolower(trim($email)));
}
```

**Comment by awcodes** [comment]
Why is email null? Gravatar requires an email to work properly.

**Comment by syzygyinteractivemedia** [comment]
I think because i use filament tenancy with an other model than User…? 

Also the function parameter accepts null (and sets as default null…
